### ISSUE TITLE
Is the Problem resolved?????

### ISSUE THREAD

**Issue by yezi34880** [DominikAmon/RclIssueDemo#1]
Is the Problem resolved?????

**Comment by DominikAmon** [comment]
Yes, this problem is solved.
It is important to remove:
`<PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.2.0" />`

See the discussion at Stackoverflow: https://stackoverflow.com/a/60740042/1099519

**Comment by yezi34880** [comment]
thank yuo 
I tried some other solutions, finally solved the problem by change the js and css to the EmbeddedResource 
and it is used in main project as well 
but there is another problem do you have
when i debug , the modify can't show real time,
I use the AddRazorRuntimeCompilation ,it resolved the razor page (  .cshtml ) but not the js and css files,
I only can close debug and rebuild the module and restart , is's very complex
do you have a easy way to debug RCL
